

--- # Local
spring:
  config:
    activate:
      on-profile: "logger-local"
logging:
  config: classpath:loggerProps/local.yaml
  level:
    root: debug
    org:
      springframework:
        web: debug
        sql: error
        jdbc: off
        jdbc.sqlonly: debug
  file:
    name: classpath:logs/log.log
